### PR TITLE
Chronologicals

### PR DESCRIPTION
**Pull request by tobibaum**
Eh...or do we rather want to push to master directly with the writeups?

### CODE REVIEW

**Comment by sergeyk** [comment]
I think we just want to commit into master for writeups. Why is this a separate document instead of a section in proposal.tex?

**Comment by tobibaum** [comment]
It's not quite done yet. Will merge it into proposal later today.

On Mon, Mar 12, 2012 at 11:56 AM, Sergey Karayev <
reply@reply.github.com

**Comment by ronsun669** [comment]
Could you clarify what u mean?
On Mar 12, 2012 11:19 AM, "Tobias Baumgartner" <
reply@reply.github.com>
wrote:

**Comment by tobibaum** [comment]
I created a topic branch for this piece of the writeup, where we should
actually just work on the master I guess.

On Mon, Mar 12, 2012 at 1:05 PM, Ron <
reply@reply.github.com

**Pull request merged**
